version: "3.8"
name: 'lottery'
services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    image: 'php:8.2-fpm-alpine'
    volumes:
      - ./:/var/www/html:delegated
  